site_name: Philibert OLLIER
site_url: https://philibert.io
site_description: "Cloud Architect & DevOps Engineer"
theme:
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
  name: material
  icon:
    logo: material/cloud-braces
  custom_dir: docs/overrides

  palette:
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - social
  - print-site:
      add_to_navigation: false
      add_print_site_banner: false
      add_table_of_contents: false
      print_page_title: "Philibert OLLIER"
      path_to_pdf: "/Philibert_OLLIER.pdf"
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: false
      cover_page_template: ""
      include_css: true
      enabled: true
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
