[project]
name = "ollier-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material",
    "mkdocs-material[imaging]",
    "mkdocs-print-site-plugin",
    "nodeenv",
]
